services:
  web-ui:
    container_name: web-ui
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "5000:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - open-webui-local:/app/backend/data

  ollama:
    container_name: ollama
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama-local:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all

  agno:
    container_name: agno
    build:
      context: ./agno
    environment:
      - OLLAMA_HOST=${OLLAMA_HOST}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    tty: true
    ports:
      - "7777:7777"
    volumes:
      - ./agno/src:/app

  agent-ui:
    container_name: agent-ui
    build:
      context: ./agent-ui
    ports:
      - "3000:3000"
    tty: true
    volumes:
      - agent-ui-data:/app/agent-ui

  pgvector:
    container_name: pgvector
    image: agnohq/pgvector:16
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ai
      - POSTGRES_USER=ai
      - POSTGRES_PASSWORD=ai
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - pgvolume:/var/lib/postgresql/data

volumes:
  ollama-local:
  open-webui-local:
  pgvolume:
  agent-ui-data:
